In [1]:
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [2]:
spam_folders = ["../data/SPAM/enron%d/spam/" % i for i in range(1, 7)]
ham_folders = ["../data/SPAM/enron%d/ham/" % i for i in range(1, 7)]

text = []
y = []
for spam_folder in spam_folders:
    for fname in os.listdir(spam_folder):
        with open(os.path.join(spam_folder, fname), 'r', encoding='latin') as f:
            text.append(f.read())
            y.append(1)

for ham_folder in ham_folders:
    for fname in os.listdir(ham_folder):
        with open(os.path.join(ham_folder, fname), 'r', encoding='latin') as f:
            text.append(f.read())
            y.append(0)

In [3]:
text_train, text_test, y_train, y_test = train_test_split(text, y)

In [4]:
np.array(y_train)

array([1, 1, 1, ..., 0, 1, 0])

In [5]:
count_vec = CountVectorizer(token_pattern=r'\b[^\d\W]+\b')
X_train = count_vec.fit_transform(text_train)
X_test = count_vec.transform(text_test)

In [6]:
np.array(count_vec.get_feature_names())[np.argsort(X_train.sum(axis=0).A1)[::-1][:10]]

array(['the', 'to', 'and', 'of', 'a', 'in', 'for', 'you', 'is', '_'],
      dtype='<U24')

In [7]:
np.argsort(X_train.sum(axis=0).A1)[::-1][:10]

array([109833, 111306,   4457,  78092,      1,  53887,  41653, 125024,
        56805,      0], dtype=int64)

In [8]:
model = MultinomialNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.9824415707675881
0.9851093531875291
0.9805465493283928
[[4047   64]
 [  84 4234]]


In [9]:
tfidf_vec = TfidfVectorizer(token_pattern=r'\b[^\d\W]+\b')
X_train = tfidf_vec.fit_transform(text_train)
X_test = tfidf_vec.transform(text_test)

C:\Users\ztypl\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:1089: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):
