In [47]:
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [9]:
spam_folders = ["../data/SPAM/enron%d/spam/" % i for i in range(1, 7)]
ham_folders = ["../data/SPAM/enron%d/ham/" % i for i in range(1, 7)]

text = []
y = []
for spam_folder in spam_folders:
    for fname in os.listdir(spam_folder):
        with open(os.path.join(spam_folder, fname), 'r', encoding='latin') as f:
            text.append(f.read())
            y.append(1)

for ham_folder in ham_folders:
    for fname in os.listdir(ham_folder):
        with open(os.path.join(ham_folder, fname), 'r', encoding='latin') as f:
            text.append(f.read())
            y.append(0)

In [13]:
text_train, text_test, y_train, y_test = train_test_split(text, y)

In [15]:
np.array(y_train)

array([0, 1, 1, ..., 0, 1, 0])

In [55]:
count_vec = CountVectorizer(token_pattern=r'\b[^\d\W]+\b')
X_train = count_vec.fit_transform(text_train)
X_test = count_vec.transform(text_test)

In [58]:
np.array(count_vec.get_feature_names())[np.argsort(X_train.sum(axis=0).A1)[::-1][:10]]

array(['the', 'to', 'and', 'of', 'a', 'in', 'for', 'you', 'is', '_'],
      dtype='<U24')

In [42]:
np.argsort(X_train.sum(axis=0).A1)[::-1][:10]

array([119084, 120486,  16450,  87996,  64336,  52471, 133825,  67183,
       119502,  46531], dtype=int64)

In [59]:
model = MultinomialNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.9861193498635663
0.985379438384776
0.9874418604651163
[[4066   63]
 [  54 4246]]


In [ ]:
tfidf_vec = TfidfVectorizer()
